global using System.Net.Http.Json;
global using System.Text.Json.Serialization;
global using Mapster;
global using MapsterMapper;
global using Microsoft.Extensions.Configuration;
global using WeatherForecast.Core.Application.Interfaces;
global using AppCoordinatesDto = WeatherForecast.Core.Application.Dtos.Coordinates;
global using AppOpenMeteoDto = WeatherForecast.Core.Application.Dtos.OpenMeteo;
global using AppOpenMeteoGeocodingDto = WeatherForecast.Core.Application.Dtos.OpenMeteo.Geocoding;
global using InfraOpenMeteoDto = WeatherForecast.Infrastructure.ExternalService.DTOs.OpenMeteo;
global using InfraOpenMeteoGeocodingDto = WeatherForecast.Infrastructure.ExternalService.DTOs.OpenMeteo.Geocoding;
